version: '3'

services:
  leaf-disc:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    #command: Rscript run.R
    command: >
      sh -c "
        Rscript run.R &&
        make docker
      "
    container_name: leaf-disc
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    working_dir: /trait-methods
    volumes:
      - .:/trait-methods