version: '3'

services:
  analysis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    #command: ls
    #command: Rscript -e "library(tidyverse)"
    image: mattocci/leaf-disc
    command: >
      sh -c "
        Rscript run.R &&
        make docker
      "
    container_name: leaf-disc
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    working_dir: /home/rstudio/leaf-disc
    volumes:
      - .:/home/rstudio/leaf-disc
