```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  cache = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r, include = FALSE}
library(tidyverse)
library(patchwork)
library(ggsma)
```

# Make clean tree-level data

- New data 2021 August

$$
log(X) \sim N(\mu, \sigma)
$$

then,

$$
CV(X) = \sqrt{exp(\sigma^2) - 1}
$$


```{r new-data}
d <- read_csv("../data-raw/LMA_Raw.csv")

cv <- \(x, na.rm = TRUE) sd(log(x), na.rm = TRUE) / mean(log(x), na.rm = TRUE)
# cv <- \(x) sqrt(exp(sd(log(x[!is.na(x)]))^2) - 1)

d <- d |>
  mutate(Location = ifelse(Location == "Ailao_underground", "Ailao_understory", Location)) |>
  filter(!is.na(Species)) |>
  filter(!is.na(LMAdisc)) |>
  # 0.6 cm: 0.3^2 * pi * 3 disc = 0.848
  mutate(LMAdisc = LMAdisc * 0.899 / 0.848) |>
  mutate(Species = str_replace_all(Species, "\\?", " ")) |>
  mutate(ID2 = paste(ID, Rep, sep = "-"))

hist(d$LDMCleaf)

sp_dat <- d |>
  group_by(Species, Location) |>
  summarise_at(
    .vars = vars(
      LMAdisc,
      LMAleaf,
      LDdisc,
      LDleaf,
      LTleaf,
      LTdisc,
      Leaf_area_leaf
    ),
    .funs = cv
  )

sp_list <- d |>
  dplyr::select(Species:`Data contributor`) |>
  unique()

new_dat <- full_join(sp_list, sp_dat, by = c("Species", "Location")) |>
  rename(LAleaf = Leaf_area_leaf) |>
  rename(contributor = `Data contributor`) |>
  mutate(Garden = "NO")

d_tree <- d |>
  dplyr::select(
    "ID" = ID2,
    "Species",
    "Family",
    "Growthform" = Growth_form,
    "EveDec" = Leaf_habit,
    "Leaf_type",
    "Location",
    "Biomes",
    "Contributor" = `Data contributor`,
    "LMAdisc",
    "LMAleaf",
    "LDdisc",
    "LDleaf",
    "LTleaf",
    "LTdisc",
    "LAleaf" = Leaf_area_leaf
  )
```


# Yakushima

- join yakushima data


```{r, yakushima}
d3 <- read_csv("../data-raw/leaf_traits_for_Katabuchi.csv")

yaku <- d3 |>
  filter(Growthform != "H") |>
  mutate(Location = "Yakushima") |>
  mutate(Biomes = "ST2") |>
  mutate(Garden = "NO") |>
  mutate(MAT = NA) |>
  mutate(MAP = NA) |>
  mutate(Contributor = "Onoda Yusuke") |>
  rename(
    LA = `LA mean (leaf let)`,
    LT = `Lamina thickness`,
    LMAdisc = `LD LMA`,
    LMAleaf = `Whole leaf LMA`,
    # LDMCleaf = `LDMC`,
    LDdisc = `TD`
  ) |>
  mutate(LDleaf = LMAleaf / LT * 10^-3) %>%
  # mutate(LDMCdisc = NA) |>
  mutate(LTdisc = NA) |>
  mutate(Growthform = ifelse(Growthform == "W", "Trees", Growthform))

yaku_sp <- yaku |>
  group_by(Species) |>
  summarize(
    Family = APG.family,
    Growthform,
    EveDec,
    Location,
    Biomes,
    Garden,
    #  MAT,
    #  MAP,
    Contributor,
    LMAdisc = cv(LMAdisc),
    LMAleaf = cv(LMAleaf),
    # LDMCdisc = LDMCdisc,
    # LDMCleaf = cv(LDMCleaf, na.rm = TRUE),
    LDdisc = cv(LDdisc),
    LDleaf = cv(LDleaf),
    LT = cv(LT),
    LTdisc = cv(LTdisc),
    LA = cv(LA)
  ) |>
  unique()


new_dat3 <- full_join(new_dat, yaku_sp,
  by = c("Species", "Family", "Location", "Biomes",
    "LMAdisc", "LMAleaf",
    "LDleaf",
    # "LDMCdisc",
    "Growth_form" = "Growthform",
    "Leaf_habit" = "EveDec",
    "contributor" = "Contributor",
    "LDdisc",
    "LTleaf" = "LT",
    "LAleaf" = "LA",
    # "LDMCleaf",
    "Garden",
    # "MAT", "MAP",
    "LTdisc"
  )
) |>
  rename(Contributor = contributor)

new_dat3 |>
  dplyr::select(
    Species,
    Family,
    Growth_form,
    Leaf_habit,
    Leaf_type,
    Location,
    Garden,
    # MAT,
    # MAP,
    Biomes,
    Contributor,
    LMAdisc,
    LMAleaf,
    LDdisc,
    LDleaf,
    # LDMCdisc,
    # LDMCleaf,
    LTleaf,
    LTdisc,
    LAleaf
  ) |>
  rename(Growthform = Growth_form) |>
  rename(EveDec = Leaf_habit) |>
  rename(LeafType = Leaf_type) |>
  mutate(LeafType = case_when(
    LeafType == "single" ~ "S",
    LeafType == "compound" ~ "C"
  )) |>
  write_csv("../data/full_data_cv.csv")


yaku_tree <- yaku |>
  dplyr::select(
    "ID" = no,
    "Species",
    "Family" = APG.family,
    "Growthform",
    "EveDec",
    "Location",
    "Biomes",
    "Contributor",
    "LMAdisc",
    "LMAleaf",
    "LDdisc",
    "LDleaf",
    "LTleaf" = LT,
    "LAleaf" = LA
  )

full_join(d_tree, yaku_tree,
  by = c(
    "ID", "Species", "Family", "Growthform", "EveDec", "Location",
    "Contributor",
    "Biomes", "LMAdisc", "LMAleaf", "LDdisc", "LDleaf", "LTleaf", "LAleaf"
  )
) |>
  write_csv("../data/tree_data.csv")
```


```{r specode, eval=FALSE, echo=FALSE}
d$Species |>
  unique() |>
  length()

sp <- d$Species |> unique()
sp <- sp[!is.na(sp)] |>
  str_replace_all("\\?", " ") |>
  unique()

sp2 <- str_to_upper(sp) |>
  str_split_fixed(" ", 2) |>
  apply(2, \(x) str_sub(x, 1, 3))

sp3 <- paste0(sp2[, 1], sp2[, 2])

sp_dat <- tibble(sp, sp3)

sp_dat_f <- sp_dat |>
  filter(sp3 %in% sp3[duplicated(sp3)]) |>
  arrange(sp)

spcode <- sp_dat |>
  mutate(SPCODE = case_when(
    sp == "Croton tiglium spp. A" ~ "CROTI1",
    sp == "Croton tiglium spp. B" ~ "CROTI2",
    sp == "Millettia pachycarpa" ~ "MILPA1",
    sp == "Millettia pachyloba" ~ "MILPA2",
    sp == "Ptychosperma macarthurii" ~ "PTYMA1",
    sp == "Ptychosperma macrospadix" ~ "PTYMA2",
    TRUE ~ sp3
  )) |>
  rename(Species = sp) |>
  dplyr::select(sp, SPCODE)

full_join(d, spcode, by = )

sp |> length()
sp3 |>
  unique() |>
  length()

sp3[duplicated(sp3)]

str_sub(sp, 1, 3)

d$ID |>
  unique() |>
  length()
```
